name:                goals-tracker
version:             0.1.0.0
github:              "lfborjas/goals-tracker"
license:             BSD3
author:              "Luis Borjas Reyes"
maintainer:          "luis@lfborjas.com"
copyright:           "2019 Luis Borjas Reyes"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lfborjas/goals-tracker#readme>

dependencies:
- base >= 4.7 && < 5
- bytestring
- text
- http-conduit
- aeson
- wreq
- lens
- lens-aeson
- directory
- sqlite-simple
- gi-gtk
- gi-gtk-declarative
- gi-gtk-declarative-app-simple
- Chart
- Chart-cairo
- cairo
- gi-cairo
- time
- data-default-class
- colour
- transformers

# Note that the gi-gtk* dependencies are in stack.yml
# since that package isn't in the LTS (stackage)
# in fact, I had to _manually_ add them to the cabal file??

library:
  source-dirs: src

executables:
  goals-tracker-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -XOverloadedStrings
    dependencies:
    - goals-tracker

tests:
  goals-tracker-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - goals-tracker
